# Generated by Django 3.2.4 on 2021-10-26 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrone', '0003_alter_userprofileinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='public_day',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
