# Generated by Django 3.2.4 on 2021-10-26 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrone', '0004_alter_drone_public_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='public_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
