# Generated by Django 3.2.4 on 2021-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrone', '0005_alter_drone_public_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
