# Generated by Django 3.2.4 on 2021-10-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrone', '0006_drone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
    ]
