# Generated by Django 3.2.4 on 2021-10-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydrone', '0007_alter_drone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='slug',
        ),
    ]
